# Generated by Django 5.0.6 on 2024-12-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='upload_resume',
            field=models.FileField(default=0, upload_to='resume'),
            preserve_default=False,
        ),
    ]
